version: '3'

services:

  app: 
    build: 
      context: node
    container_name: app
    command: node ./index.js
    networks:
      - app-network
    volumes:
      - ./node:/usr/src/app:default
      - node_modules:/usr/src/app/node_modules/
    tty: true
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      start_period: 1s
      interval: 2s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks: 
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 1s
      interval: 2s
      timeout: 5s
      retries: 5

  proxy:
    build: 
      context: nginx
    container_name: proxy
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  node_modules: